parameters:
  FolderPath: ''
  DisplayName: ''

steps:
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: ${{ parameters.DisplayName }}
  condition: eq(variables['DoEsrp'], 'true')
  inputs:
    ConnectedServiceName: 'OnnxRuntime CodeSign 20171127'
    FolderPath: ${{ parameters.FolderPath }}
    Pattern: '*.nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
     [ 
         {
             "keyCode": "CP-401405",
             "operationSetCode": "NuGetSign",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         },
         {
             "keyCode": "CP-401405",
             "operationSetCode": "NuGetVerify",
             "parameters": [ ],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
