# test NuGet package on Win, Linux and MacOS
parameters:
  DisableContribOps: ''
jobs:
- template: test_win.yml
  parameters:
    AgentPool : $(AgentPoolWin)
- template: test_linux.yml
  parameters:
    AgentPool : $(AgentPoolLinux)
    DisableContribOps: ${{ parameters.DisableContribOps }}
- template: test_macos.yml
  parameters:
    AgentPool : $(AgentPoolMacOS)

