# Defined as pipeline variables
# variables:
#   AgentPoolWin : 'Win-CPU-CUDA10'
#   AgentPoolLinux : 'Linux-CPU'
#   AgentPoolMacOS : 'macOS-10.13'

jobs: 
- template: templates/gpu.yml
  parameters:
    AgentPool : $(AgentPoolWin)
    DoEsrp: 'true'
